spring.application.name=parqueadero
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://switchback.proxy.rlwy.net:52810/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AyVsPNqSjGSRbYUvNLONfobPxRREQRMv}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.pool-name=ParqueaderoHikariPool
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=${APP_JWT_SECRET:CHANGE_THIS_SECRET_KEY_WITH_AT_LEAST_32_CHARS}
app.jwt.expiration-millis=${APP_JWT_EXPIRATION_MILLIS:86400000}

logging.level.saas.parqueadero=${APP_LOG_LEVEL:INFO}