CREATE TABLE cliente_instalacion (
    id bigint NOT NULL,
    activa boolean NOT NULL,
    app_version character varying(40),
    creada_en timestamp(6) with time zone NOT NULL,
    empresa_id bigint,
    estado_licencia character varying(40),
    licencia_expira_en date,
    nombre character varying(120) NOT NULL,
    tenant_id character varying(36) NOT NULL,
    token_hash character varying(64) NOT NULL,
    ultima_sync_en timestamp(6) with time zone,
    ultimo_entradas_hoy integer,
    ultimo_recaudo_hoy numeric(16,2),
    ultimo_salidas_hoy integer,
    ultimo_vehiculos_dentro integer
);

ALTER TABLE cliente_instalacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cliente_instalacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE empresa (
    id bigint NOT NULL,
    nit character varying(50) NOT NULL,
    nombre character varying(120) NOT NULL
);

ALTER TABLE empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE licencia (
    id bigint NOT NULL,
    codigo character varying(40) NOT NULL,
    emitida_por_usuario_id bigint,
    empresa_id bigint,
    estado character varying(20) NOT NULL,
    fecha_emision timestamp(6) without time zone NOT NULL,
    fecha_expiracion date NOT NULL,
    fecha_redencion timestamp(6) without time zone,
    fecha_revocacion timestamp(6) without time zone,
    nota character varying(500),
    prueba boolean,
    version bigint,
    CONSTRAINT licencia_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'REDIMIDA'::character varying, 'REVOCADA'::character varying])::text[])))
);

ALTER TABLE licencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME licencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token_hash character varying(100) NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE registro_parqueo (
    id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_entrada timestamp(6) without time zone NOT NULL,
    fecha_salida timestamp(6) without time zone,
    placa character varying(15) NOT NULL,
    sede_id bigint NOT NULL,
    tipo_vehiculo character varying(20) NOT NULL,
    total_pagado numeric(14,2),
    usuario_id bigint NOT NULL,
    CONSTRAINT registro_parqueo_estado_check CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'FINALIZADO'::character varying])::text[]))),
    CONSTRAINT registro_parqueo_tipo_vehiculo_check CHECK (((tipo_vehiculo)::text = ANY ((ARRAY['CARRO'::character varying, 'MOTO'::character varying])::text[])))
);

ALTER TABLE registro_parqueo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME registro_parqueo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE sede (
    id bigint NOT NULL,
    capacidad_actual integer NOT NULL,
    capacidad_total integer NOT NULL,
    empresa_id bigint NOT NULL,
    nombre character varying(120) NOT NULL
);

ALTER TABLE sede ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sede_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE snapshot_operativo (
    id bigint NOT NULL,
    app_version character varying(40),
    entradas_hoy integer,
    estado_licencia character varying(40),
    generado_en timestamp(6) with time zone,
    payload jsonb NOT NULL,
    recaudo_hoy numeric(16,2),
    recibido_en timestamp(6) with time zone NOT NULL,
    salidas_hoy integer,
    tenant_id character varying(36) NOT NULL,
    vehiculos_dentro integer
);

ALTER TABLE snapshot_operativo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME snapshot_operativo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE suscripcion_mensual (
    id bigint NOT NULL,
    activa boolean NOT NULL,
    alerta_vencimiento_enviada boolean DEFAULT false NOT NULL,
    empresa_id bigint NOT NULL,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    placa character varying(15) NOT NULL,
    sede_id bigint NOT NULL,
    telefono character varying(20),
    tipo_vehiculo character varying(20) NOT NULL,
    valor_mensual numeric(14,2) NOT NULL,
    CONSTRAINT suscripcion_mensual_tipo_vehiculo_check CHECK (((tipo_vehiculo)::text = ANY ((ARRAY['CARRO'::character varying, 'MOTO'::character varying])::text[])))
);

ALTER TABLE suscripcion_mensual ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME suscripcion_mensual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tarifa (
    id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    minutos_fraccion integer NOT NULL,
    sede_id bigint NOT NULL,
    tipo_vehiculo character varying(20) NOT NULL,
    valor_fraccion numeric(14,2) NOT NULL,
    CONSTRAINT tarifa_tipo_vehiculo_check CHECK (((tipo_vehiculo)::text = ANY ((ARRAY['CARRO'::character varying, 'MOTO'::character varying])::text[])))
);

ALTER TABLE tarifa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tarifa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE usuario (
    id bigint NOT NULL,
    empresa_id bigint,
    nombre character varying(120),
    password character varying(255) NOT NULL,
    rol character varying(30) NOT NULL,
    sede_id bigint,
    username character varying(80) NOT NULL,
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'OPERARIO'::character varying])::text[])))
);

ALTER TABLE usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY cliente_instalacion
    ADD CONSTRAINT cliente_instalacion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY cliente_instalacion
    ADD CONSTRAINT idx_cliente_instalacion_tenant UNIQUE (tenant_id);

ALTER TABLE ONLY licencia
    ADD CONSTRAINT licencia_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY registro_parqueo
    ADD CONSTRAINT registro_parqueo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sede
    ADD CONSTRAINT sede_pkey PRIMARY KEY (id);

ALTER TABLE ONLY snapshot_operativo
    ADD CONSTRAINT snapshot_operativo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY suscripcion_mensual
    ADD CONSTRAINT suscripcion_mensual_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tarifa
    ADD CONSTRAINT tarifa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY licencia
    ADD CONSTRAINT uk4d17mrgn9ngw1mxkw6jtsed7e UNIQUE (codigo);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY tarifa
    ADD CONSTRAINT uk_tarifa_sede_empresa_tipo UNIQUE (sede_id, empresa_id, tipo_vehiculo);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT uk_usuario_username_empresa UNIQUE (username, empresa_id);

ALTER TABLE ONLY empresa
    ADD CONSTRAINT uka344uhvvn5iuti0u46a2e8no9 UNIQUE (nit);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

CREATE INDEX idx_cliente_instalacion_empresa ON cliente_instalacion USING btree (empresa_id);

CREATE INDEX idx_refresh_token_usuario ON refresh_token USING btree (usuario_id);

CREATE INDEX idx_registro_estado ON registro_parqueo USING btree (estado);

CREATE INDEX idx_registro_placa_sede_empresa ON registro_parqueo USING btree (placa, sede_id, empresa_id);

CREATE INDEX idx_sede_empresa ON sede USING btree (empresa_id);

CREATE INDEX idx_snapshot_tenant_recibido ON snapshot_operativo USING btree (tenant_id, recibido_en);

CREATE INDEX idx_suscripcion_activa ON suscripcion_mensual USING btree (activa);

CREATE INDEX idx_suscripcion_placa_empresa_sede ON suscripcion_mensual USING btree (placa, empresa_id, sede_id);

CREATE INDEX idx_tarifa_empresa_sede ON tarifa USING btree (empresa_id, sede_id);

CREATE INDEX idx_usuario_empresa ON usuario USING btree (empresa_id);
