-- Clientes (destinatarios de notificaciones), cuenta de WhatsApp por empresa y bitacora de mensajes.

CREATE TABLE cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    nombre character varying(120) NOT NULL,
    telefono character varying(20) NOT NULL,
    -- Consentimiento: ningun cliente recibe WhatsApp hasta que se habilite expresamente
    whatsapp_habilitado boolean DEFAULT false NOT NULL,
    pref_facturacion boolean DEFAULT true NOT NULL,
    pref_mensualidades boolean DEFAULT true NOT NULL,
    pref_confirmaciones_pago boolean DEFAULT true NOT NULL,
    pref_operativas boolean DEFAULT false NOT NULL,
    creado_en timestamp(6) with time zone DEFAULT now() NOT NULL,
    actualizado_en timestamp(6) with time zone DEFAULT now() NOT NULL,
    CONSTRAINT uk_cliente_empresa_telefono UNIQUE (empresa_id, telefono)
);

CREATE INDEX idx_cliente_empresa ON cliente (empresa_id);

ALTER TABLE suscripcion_mensual ADD COLUMN cliente_id bigint;
CREATE INDEX idx_suscripcion_cliente ON suscripcion_mensual (cliente_id);

-- Los clientes de las mensualidades existentes se crean sin consentimiento de WhatsApp.
INSERT INTO cliente (empresa_id, nombre, telefono)
SELECT empresa_id, 'Cliente ' || min(placa), telefono
FROM suscripcion_mensual
WHERE telefono ~ '^\+[1-9][0-9]{1,14}$'
GROUP BY empresa_id, telefono;

UPDATE suscripcion_mensual s
SET cliente_id = c.id
FROM cliente c
WHERE c.empresa_id = s.empresa_id
  AND c.telefono = s.telefono;

CREATE TABLE whatsapp_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    provider character varying(20) DEFAULT 'META' NOT NULL,
    waba_id character varying(64) NOT NULL,
    business_id character varying(64),
    phone_number_id character varying(64) NOT NULL,
    display_phone_number character varying(32) NOT NULL,
    -- Token de acceso cifrado (AES-GCM); nunca se devuelve por la API
    access_token_encrypted text NOT NULL,
    status character varying(20) NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_whatsapp_account_empresa UNIQUE (empresa_id),
    CONSTRAINT uk_whatsapp_account_phone UNIQUE (phone_number_id)
);

CREATE TABLE whatsapp_message (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    whatsapp_account_id bigint,
    cliente_id bigint,
    suscripcion_id bigint,
    destination character varying(32) NOT NULL,
    message_type character varying(40) NOT NULL,
    template_name character varying(80) NOT NULL,
    template_variables text,
    provider_message_id character varying(128),
    status character varying(20) NOT NULL,
    requested_at timestamp(6) with time zone NOT NULL,
    provider_accepted_at timestamp(6) with time zone,
    sent_at timestamp(6) with time zone,
    delivered_at timestamp(6) with time zone,
    read_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    error_code character varying(40),
    error_message character varying(500),
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_whatsapp_message_empresa_fecha ON whatsapp_message (empresa_id, requested_at);
CREATE INDEX idx_whatsapp_message_suscripcion ON whatsapp_message (suscripcion_id, message_type);
CREATE UNIQUE INDEX uk_whatsapp_message_provider_id ON whatsapp_message (provider_message_id)
    WHERE provider_message_id IS NOT NULL;
